package com.morgrimm.osteomancy.tileentity;

public enum EnumVatWallTypes {
    vatWallNormal,
    vatWallMaster,
    vatWallBotLeftCorner1,
    vatWallBotRightCorner1,
    vatWallBotLeftCorner2,
    vatWallBotRightCorner2,
    vatWallMiddleLeftCorner1,
    vatWallMiddleRightCorner1,
    vatWallMiddleLeftCorner2,
    vatWallMiddleRightCorner2,
    vatWallTopLeftCorner2,
    vatWallTopRightCorner2,
    vatWallTopLeftCorner1,
    vatWallTopRightCorner1,
    vatWallMiddle1,
    vatWallMiddle2,
    vatWallMiddle3,
    vatWallMiddle4,
    vatWallMiddle5,
    vatWallMiddle6,
    vatWallMiddle7,
    vatWallMiddle8,
    vatWallMiddle9,
    vatWallMiddle10,
    vatWallMiddle11,
    vatWallMiddle12;
}
